ministryofjustice/intranet

README.md
This is not applicable to this version of the repo and could be
misleading.
=> Deprecate CircleCI integration

docker/build.sh
The mkdir is failing, because the intermediate directory doesn't
exist. This should fix that.
=> Add missing -p option to mkdir

docker/config/environments/development.php
WP was displaying all errors in whatever it considered a 'page', even if
this meant putting an html snippet into a JSON response.  This change
ensures that the errors only show up in the docker logs.
=> Prevent errors from breaking REST api in dev

docker/Makefile
This wipes the local slate clean, wrt docker images and compiled
assets (although the local data volume is left intact).
=> Add a 'nuke-all' make target

docker/Makefile
Fixes a typo that raises an error when running `make prepare-wordpress-database`
=> `make restart yas3fs` -> `make restart-yas3fs`

docker/utils/prepare-local-wordpress-database.rb
Now you can set `INTRANET_DOMAIN` if you don't want the
`http://intranet.docker` default and the script will show you before and
after counts of the various SQL substitutions.
=> Make domain change easier and errors more visible

docker/etc/nginx/sites-available/server.conf
This uses the forwarded protocol header to determine if a redirect is
required, so it *shouldn't* end us up in an endless redirect loop.
=> Fix the broken http -> https redirect on AWS

docker/etc/nginx/sites-available/server.conf
It appears that `$http_x_forwarded_proto != "https"` matches when
`$https_x_forwarded_for` is not set.  This changes the rule to require
an explicit match against `http` and fixes the problem on local
container builds.
NOTE: If you've run the last version, you will need to flush your cache,
or check `http://intranet.docker` in another browser as the redirect is
permanent.
=> Fix the overactive http -> https redirect

docker/build.sh, docker/etc/nginx/sites-available/server.conf, docker/web/403.html
The replaces the default, and very uninformative, nginx 403 error page
with something that gives the support email. This will ensure that users
on yet-to-be whitelisted IPs will know how to get in touch to gain
access.
=> Ensure users can report additional whitelist ips

docker/etc/nginx/sites-available/server.conf
The new 403 error page was refusing to show when the site was deployed
via pipline. This was because that the page, itself, was falling under
whitelist control; the server fallback was to show the standard nginx
403 page.  This fixes that by ensuring that `/403.html` is accessible to
all.
=> Ensure the informative 403 page always shows

docker/etc/nginx/sites-available/server.conf
For reasons that are not clear, `location /wp-admin {...` is refusing to
match paths with filenames.  This means that login paths like
`/wp-admin/post-new.php?post_type=post` do not redirect correctly with
the original configuration.  Adding an explicit prefix-matching
operator (`location ^~ /wp-admin {...` and contextualising the rewrite
rule to the block (`rewrite_rule ^/wp-admin...` -> `rewrite_rule
^/(.*)...`) fixes this problem.
=> Redirect all requests for /wp-admin correctly

docker/etc/nginx/sites-available/server.conf
The images are failing a CORS preflight, so I've added a very permissive
CORS config to get them working for the time being.  We'll review and
tighten this up early next week.
=> Make images display on www.intranet.justice.gov.uk

docker/etc/nginx/sites-available/server.conf
This was supposed to make images work on
www.intranet.justice.gov.uk but it had the effect of breaking
intranet.justice.gov.uk instead
=> Revert the attempted CORS fix

docker/etc/nginx/sites-available/server.conf
CORS breaks images when a user views the site on
www.intranet.justice.gov.uk.  This is the simplest possible fix for the
problem–far less invovled, and far more secure, than a complex CORS
config.
=> Fix the broken js images issue in the simplest way

docker/etc/php/7.1/fpm/pool.d/pool.conf
The 502/504 errors we are seeing on the AWS prod enviroment seem to stem
from the very conservative fpm settings from the base container.  After
discussing with DS, we agreed to raise the limits.  I am starting with
5 processes and 15 processes maximum.  I am also setting a respawn limit
of 1500 requests in case DXW were dealing with memory leaks that we were
not made aware of.
=> Fix gateway errors that result from FPM timeouts

docker/Dockerfile, docker/etc/nginx/sites-available/server.conf, docker/etc/php/7.1/fpm/pool.d/pool.conf
It appears cloudwatch has very limited search capabilities for non-json
formatted logs–simple wildcards only. JSON formatted logs, however,
have a much more sophsiticated search DSL.  This should make it much
easier to find things in the logs.
I have also enabled the fpm slow log in an effort to track down the
cause of the remaining 504s and slow event feed load times.  The setting
I've chosen are aggressive–they may need review after a few days.  Also,
it is worth noting that triggering this log locally is tricky.  As a
result, I do not know its format, so it may be diffcult to search on
cloudwatch. There does not seem to be a simple way to configure it to
output json.  I will experiment with doing so if it becomes necessary.
=> Make logs searchable; Enable fpm slow log

wp-content/themes/mojintranet/page_error.php
so error page doesn’t instruct to be cached for 24h
=> Removed headers setting cache to 24h

wp-content/themes/mojintranet/inc/cache.php, wp-content/themes/mojintranet/inc/headers.php, wp-content/themes/mojintranet/page_about_us.php, wp-content/themes/mojintranet/page_blog.php, wp-content/themes/mojintranet/page_campaign_content.php, wp-content/themes/mojintranet/page_campaign_landing.php, wp-content/themes/mojintranet/page_error.php, wp-content/themes/mojintranet/page_events.php, wp-content/themes/mojintranet/page_generic.php, wp-content/themes/mojintranet/page_guidance_and_support.php, wp-content/themes/mojintranet/page_guidance_and_support_index.php, wp-content/themes/mojintranet/page_home.php, wp-content/themes/mojintranet/page_media_grid.php, wp-content/themes/mojintranet/page_news.php, wp-content/themes/mojintranet/page_regional_events.php, wp-content/themes/mojintranet/page_regional_landing.php, wp-content/themes/mojintranet/page_regional_news.php, wp-content/themes/mojintranet/page_search_results.php, wp-content/themes/mojintranet/single-event.php, wp-content/themes/mojintranet/single-news.php, wp-content/themes/mojintranet/single-post.php, wp-content/themes/mojintranet/single-regional_news.php, wp-content/themes/mojintranet/single-webchat.php, wp-content/themes/mojintranet/user.php
The Content team expect that newly published articles will appear on the
site within 60 seconds of publication.  Due to the aggressive nature of
browser caching, and our varying `cache_timeout` settings, this was
frequently not the case.  This change ensures that all caching will be
done for 60 seconds.
I started by making all of the `cache_timeout` settings equal to 60,
then I realised this could be DRY'd out by simply removing them and
setting the default timeout to 60 seconds.  I replaced the
`cache_timeout` key for error pages, only-set to zero seconds, this
continues to prevent the error pages from caching by sending max-age=0;
This *may* cause performance problem on production, so we should monitor
server performance for some time after it is released.
=> Ensure caching meets expectations of end users

wp-content/themes/mojintranet/models/likes.php
This method *always* return true regardless of input and was therefore.
Removing it shortens `like.php` and makes it more efficient and easier
to maintain.
=> Make debugging of like functionality simpler

docker/moj.json
@tatyree could you review? Breadcrumb functionality doesn't come out of the box with Wordpress. A decision had to be made between writing an in-house custom breadcrumb plugin for the new Clarity theme or using a third party plugin. After consultation with TP and Vinh, this looks to be the more favoured approach. Installing this plugin now won't affect the current site, but it will be required for any new Clarity templates we launch.
=> Added breadcrumb plugin NavXT for use in the new Clarity theme.

docker/utils/find-pages-with-broken-links.sh
This script only inspects content and report which pages/posts contain
links to the old `moj-wp-prod` bucket.  It does not attempt to check the status of
existing links.
=> Add script to find broken s3 links to utils

wp-content/themes/mojintranet/inc/images.php
This is causing agency editors a lot of problems. These problems are
having a knock-on effect on the team in that we are getting requests to
upload/manage banners, which the editors should be able to do for
themselves.  Removing these restrictions should solve that problem at
the potential risk of introducing issues with mis-sized images.
However, that is an editorial issue.
=> Remove image size restrictions

wp-content/themes/mojintranet/assets/css/src/modules/_posts.scss
The .post-widget class controls the display of blog posts on an agency's homepage. This change set's the class to not display when viewed by a Judicial Office user.
=> Removed Blog posts from appearing on the JO homepage.

wp-content/themes/mojintranet/assets/css/src/modules/_main_nav.scss
I've done this in keeping with how the old site's approached to menu buttons. A CSS class hides the button in question from every agency except the one you specify - in this case a custom Blog menu item for the JO that allows for the custom blog link they wanted. Included in this commit is hiding the default blog menu button. Without this, you would have two blog buttons in the menu when visiting as a JO user.
=> Added CSS logic to only display custom JO blog menu button. 

.gitignore, docker/build.sh
This appears to be happening on the fly and automagically in dev, but
not at all in production.  This *should* make the behaviour consistent
between the two.
=> Ensure clarity assets get build in production

wp-content/themes/mojintranet/views/email/activate_account.php, wp-content/themes/mojintranet/views/pages/user/activate/request_activation_link_confirmation.php
The links have been observed to be active for more than three hours. Given that access is whitelisted, and the commentor is required to have a `justice.gov.uk` address, the security risk that arises because timeout is **not** functioning is very low.  As per our pre-Christmas planning, I am
removing the copy concerning the expiry from the app.
=> Removed copy re. 3 hour limit on commenting links

docker/moj.json
I knew about this, but forgot to replace it when I made the previous
merge.
=> Replace a missing curly brace

docker/moj.json
This is needed because the clarity theme and the WP update branch are
diverging.  Needs to be addressed before it becomes a problem.
=> Change the branch of clarity used

docker/moj.json
This got missed on the AWS switchover and is required to ensure images
for non-editorial users get served directly from the S3 bucket and not
from the WP instance, itself.
=> Install Ollie's s3 rewriting plugin

docker/moj.json
removing the premium version. as it was conflicting with the wordpress core API
updated to the latest free version because we didn't have login details to download the latest premium version.
Latest free version is now working with WP core api
=> installed latest version of relevanssi

.travis.yml, README.md, docker/docker-compose-smoketest.yml, smoke-tests/Dockerfile, smoke-tests/Gemfile, smoke-tests/README.md, smoke-tests/features/happypath/c-login_agency_editor.feature, smoke-tests/features/happypath/c-quick-links_editor.feature, smoke-tests/wait-for-wordpress.sh
These got left a long time due to team changes and other external factors.  This re-enables them as a standalone set of docker containers that deal with every aspect of the Intranet install: WP, the database, an smtp emulator and the smoketests, themselves.
=> Fix and re-enable smoketests. 

docker/Dockerfile
This appears to have started happening with a recent update somewhere
further up the container chain.  Adding/updating the libffi-dev libs
seems to fix it.
=> Install libffi-dev to stop sass gem failing

docker/etc/php/7.1/fpm/pool.d/pool.conf
Since changing the memory settings, memory utilisation has fallen from
~115% to ~68%.  I'm increasing the number of childern in a effort to
increase performance.
=> Increase fpm children per container

docker/etc/php/7.1/fpm/pool.d/pool.conf
I **supect** that the 502 errors we are seeing are the result of a
mismatch between the number of nginx workers and the fpm workers.  I'm
putting the number of fpm workers back down to 20, and reducing their
lifespan (2000 requests to 1500 requests before a worker is replaced)
to see if that stops these errors.
=> Reduce max_children and max_requests

docker/etc/php/7.1/fpm/pool.d/pool.conf
I believe this is what is causing the current spate of 502 errors. The documentation
(http://php.net/manual/en/install.fpm.configuration.php) strongly
suggests it overrides `max_execution_time`, which is set to 30 seconds.
If it does, then that would explain why we are seeing so many 502 errors
since I changed the fpm configurations.  It would also explain why it is
nearly impossible to upload a document right now-a typical document is
very, very likely to take more than 5 seconds to upload.
=> Remove the request_terminate_timeout setting

docker/etc/nginx/sites-available/server.conf
When caching is activated and the user changes agency, most of the pages
get stuck with the wrong agency header.  I suspect the problem lies in
the fastcgi cache on nginx because two different users making sequential
requests will both recieve the same, incorrect, header.  This will
always be the header of the first user's request.  As the fastcgi cache
*seems* to be obeying `Cache-Control` headers, and there is no other
intermediate cache (it only caches on the end-users' browsers or nginx
on the local containers), I surmise the wrong information must be
getting stored in the fastcgi cache.  This *should* fix the problem.
=> Extract dw_agency cookie value and add to cache path

docker/etc/php/7.1/fpm/pool.d/pool.conf
Right now, we only get the nginx logs on the AWS enviroments. This is
causing problems when trying to track down certain issues. These
settings *should* ensure that the PHP logs are sent to CloudWatch as
well. The `access.log` and `error_log` settings were taken from the
official php container and the `slow_log` setting was interpreted.
=> Send all php logs to stdout

docker/etc/php/7.1/fpm/pool.d/pool.conf
This is the section where it is supposed to live.  It breaks the build
if it is in [www].
Also, turned the threshold on slowlog up to 3 seconds as I suspect it
will flood the logs otherwise.
=> Move error_log to [global]

docker/moj.json
Replaces WP Markdown plugin which was causing editors formatting issues with new markdown plugin that appears to work better.
=> Added new markdown plugin, removed old

docker/moj.json
For now we are rolling back to a version without errors.
=> Roll back breadcrumb version causing PHP notice

wp-content/themes/mojintranet/inc/redirects.php
Until we are able to disable the MVC we should keep these redirects in place, removing them may cause old pages to not redirect correctly.
=> Added redirects back into old theme

wp-content/themes/mojintranet/admin/editor-enhancements.php
The region section of the website is tied closely into the autocomplete function used on the admin backend to select a parent page for the page you are editing. When we removed the legacy code, it removed the code used for the autocomplete admin meta box. This reinstates that code, however it will soon need to be refactored once we make changes to both the template system and when we remove MVC.
=> Re-added admin autocomplete to select parent page

docker/etc/nginx/sites-available/server.conf, docker/etc/nginx/snippets/headers.conf
Missing 'Strict-Transport-Security' header, force browser to communicate with server via HTTPS.
=> Added additional security headers to nginx config

docker/bedrock.json, docker/moj.json
Provides support to our Query Monitor plugin. This introduces Gutenberg but with a fall back to the "classic" editor interface.
=> Updated plugins and WP to latest version

docker/moj.json
Someone had been using the wrong repo branch when pulling the plugin.
=> Rename repo so composer pulls correct plugin ver.

wp-content/themes/clarity/src/components/c-aside-banner/view.php
Editors voted to have the homepage image a rectangle (rather then square), the same as other
homepage images. To be constant, I've gone with the feature-thumbnail size, used across the site for similar images with the same aspect ratio.
=> Add homepage crop to banner image

wp-content/themes/clarity/inc/admin/agency_taxonomies/taxonomies/agency.php
Allow only agency admin's to be able to edit other agencies and
opt-in/out of agency content.
=> Lockdown permissions for editors

wp-content/themes/clarity/inc/admin/custom-page-attribute-box.php, wp-content/themes/clarity/page_regional_landing.php
The region landing template was not available to editors, meaning that it was not the selected template on the regional landing page and it was defaulting to the default template. 
By using the default template rather than the regional landing template,
there was a knock on effect in that the wrong breadcrumb loaded on the regional landing page. 
This was fixed, also I added a content area to regional template to account for that space being used by editors during the time they have been using the default template rather than the regional one. ..so they now have it on both.
=> Add template so page loads correct breadcrumb

wp-content/themes/clarity/inc/admin/plugins/polls.php, wp-content/themes/clarity/inc/admin/users/add-agency-admin.php, wp-content/themes/clarity/src/components/c-polls/style.styl, wp-content/themes/clarity/src/components/c-polls/view.php
TotalPolls completely refactored their poll plugin, breaking some of the
customisation work we had applied to the plugin. For example hiding
paid-for features of the plugin we are not using, in the editor view. A
warning was also thrown as the plugin had changed file names. This has
been fixed.
=> Fix and update TotalPoll plugin support

README.md, web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/agency.php
Agency Admins have the capability to add users and assign them to a
particular agency. Cat from LAA identified a bug where she was not able
to assign a new user to her agency. This fix addresses this bug.
Part of the problem was a legacy code issue, where Agency Admins could
select multipule agency views at once via checkboxes. Now this fix implements ratio
buttons allowing an agency admin editor the ability to only select one
agency view at a time.
=> User agency bug

.editorconfig, web/app/themes/clarity/inc/enqueue.php, web/app/themes/clarity/package-lock.json, web/app/themes/clarity/package.json, web/app/themes/clarity/src/components/c-feedback-form/feedback-form.js, web/app/themes/clarity/src/components/c-gallery-lightbox/feature-video.js, web/app/themes/clarity/src/components/c-left-hand-menu/left-hand-menu.js, web/app/themes/clarity/src/components/c-tabbed-content/tabbed-content.js, web/app/themes/clarity/src/globals/js/blog-content_filter.js, web/app/themes/clarity/src/globals/js/condolences-filter.js, web/app/themes/clarity/src/globals/js/equaliser.js, web/app/themes/clarity/src/globals/js/script-loader.js, web/app/themes/clarity/src/globals/js/slider.js, web/app/themes/clarity/webpack.mix.js
Readjusted Laravel mix to remove babel and process javascript files efficiently
I found a script that loads all the JavaScript objects called `script-loader.js`. It's potentially a great little script as it loads objects only when they are needed. In line with ES6 I have converted the component scripts (as well as global scripts) to exportable modules and imported them in the `script-loader.js` file as dependencies for the loader. There are 2 benefits here:
- we don't need to maintain babel anymore
- we can keep the location of script dependencies in one place
I can't see any cons for this approach, the script-loader always needs updating when a component with a script is added which is why moving dependancies here works well.
=> Fix javascript compiling errors

composer.json, composer.lock
Page Tree View Plugin has stopped working due to Jquery changes in WP 5.5 . This allows the deprecated JS to run. This is a temp fix.
=> Update Wordpress and Plugins, Adds Enable jQuery Migrate Helperplugin

web/app/themes/clarity/inc/api/get-campaign-news-api.php, web/app/themes/clarity/inc/api/get-campaign-posts-api.php, web/app/themes/clarity/inc/api/get-category-news-api.php, web/app/themes/clarity/inc/api/get-news-rest-api.php, web/app/themes/clarity/inc/api/get-posts-rest-api.php, web/app/themes/clarity/inc/content-filter/search.php, web/app/themes/clarity/inc/newscategory.php, web/app/themes/clarity/inc/pagination-newscategory.php, web/app/themes/clarity/inc/pagination.php, web/app/themes/clarity/inc/teams.php
This was causing issues with our force login plugin blocking the API.
This fix should allow us to use the plugin and have the APIs working.
=> Update APIs to use servername not localhost IP

Dockerfile
We can change this back to focal once we generate a base image that is
compatible with m1. In the meantime this is now inline with our other
sites.
=> Revert back to use same Docker base as our other sites

web/app/themes/clarity/src/components/c-register/view.php
- amended registration notification email address from intranet-support@digital.justice.gov.uk to wordpress@digital.justice.gov.uk
=> amended IT email address

composer.lock, web/app/themes/clarity/src/components/c-intranet-switcher/view.php
Since the last build took place, the plugin ACF version 5.12.3 was removed from the source and replaced. This action caused the composer shasum to be invalid.
This PR updates the ACF shasum. 
```
The checksum verification of the file failed (downloaded from https://composer.wp.dsd.io/dist/acf/advanced-custom-fields-pro/acf-advanced-custom-fields-pro-5.12.3.zip)
```
=> Fix checksum verification error

composer.json, composer.lock
The Intranet stack is failing a build.
This PR clears it by rolling back the PHP version requirement in the `composer.json` to explicit 7.4
=> Remove php8.1 requirement

.gitignore, web/app/themes/clarity/inc/acf.php, web/app/themes/clarity/inc/admin/css/acf-homepage-feature.css, web/app/themes/clarity/inc/admin/css/admin.css, web/app/themes/clarity/inc/api/get-posts-rest-api.php, web/app/themes/clarity/inc/enqueue.php
This PR improves the homepage feature search results to assist our users in finding suitable content.
The update affects [the 'Feature' tab on this administration page](https://intranet-v3.staging.wp.dsd.io/wp/wp-admin/admin.php?page=homepage-settings)
1. Order results by date and then the title
2. Display the date in the returned result
3. Remove superfluous text from page results
4. Add the parent title to the page result, if it exists
**A parent title relates to pages that are parents of sub-pages. Before this update, these are not evident or shown in the results.
=> Improve homepage feature search

web/app/themes/clarity/inc/admin/plugins/co-authors-plus.php
**Ticket:**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?modal=detail&selectedIssue=CDPT-731\
**Context:**
Some users will not allocate themselves an avatar image. This causes the co-author plugin to throw a warning, rendering the user with a broken image.
This update checks if a URL exists. If not, the code will request a default image based on their email address from Gravatar or the default Gravatar 'mystery person avatar.
http://en.gravatar.com/site/implement/images/
=> CDPT-731 Test array offset with fallback URL on false

web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/region.php
**Ticket:**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?modal=detail&selectedIssue=CDPT-732
**Context:**
Regions will (on occasion) fire an error stating that $context is undefined. I couldn't replicate the error; however, I did find a line of code that was removed in a previous PR that causes this issue:
https://github.com/ministryofjustice/intranet/commit/b4b2ee10e1e649ea9fa3c3a09f5f3b7b03254b6f#diff-5cf875bf46fc9435a41322a66ebc892638af92996a023b7d676e5ba1a318845dL254
The trouble is, without spending time tracing this code, I cannot determine what the removal of this line did or why it was done. The only impact I can determine at this stage is that the removal of the line of code is causing this issue, as the PR detailed above doesn't offer any information …
=> CDPT-732 Reset previously removed get_region_context()

web/app/themes/clarity/inc/admin/lefthand-menu.php, web/app/themes/clarity/inc/post-types/notes-from-antonia.php
**Context:**
The Notes from Antonia post-type threw the `Homepage` menu item out of position. This PR corrects this by utilising the existing menu-positioning script. It also tidies up the code a little.
The `Homepage` menu used to sit at the top of the view.
**Old layout**
**New layout, homepage menu back at the top**
=> Reorder the left-hand menu in admin panel

web/app/themes/clarity/inc/admin/lefthand-menu.php
Added regions to the custom menu ordering script.
**_Note entries below Documents:_**
> Regions are only visible when HMCTS view the admin panel. _Notes from Antonia_ is only visible when MoJ HQ are viewing; hence _Notes from Antonia_ is not visible in this menu example.
=> Adjust left-hand menu for regions

web/app/themes/clarity/inc/post-types/regional-page.php, web/app/themes/clarity/src/components/c-breadcrumbs/view-region-single.php, web/app/themes/clarity/src/components/c-breadcrumbs/view-region.php, web/app/themes/clarity/src/components/c-breadcrumbs/view.php, web/app/themes/clarity/src/components/c-tabbed-content/style.styl
This PR has a couple of treats:
1. Selectively drops a longer path in the breadcrumb, if needed
2. High-level code refactoring in a breadcrumb function
3. Flexbox has been added to tabs to assist in a clearer display for the user
* The breadcrumb was repeated
* Tabs looking displaced
---
=> CDPT 790 Fix duplicate breadcrumb path

web/app/themes/clarity/functions.php, web/app/themes/clarity/inc/admin/css/admin.css, web/app/themes/clarity/inc/admin/css/hide-document-revision-description-box.css, web/app/themes/clarity/inc/commands/DocumentRevisionReconcile.php, web/app/themes/clarity/inc/commands/NotesFromAntonia.php
**Context**
Stakeholders have been reporting 403 errors on document revisions. After investigation, it was discovered that users were removing the ID association from documents, which inadvertently lost the link to the attached revisions.
**This release does 2 things:**
1. Provides a command to fix lost documents
2. Hides the Document Description box on document post-type pages to deter users from removing the ID association.
=> CDPT-916 : document fix script - written as a command

web/app/themes/clarity/src/components/c-tabbed-content/tabbed-content.js, web/app/themes/clarity/src/globals/js/script-loader.js
**Context**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?selectedIssue=CDPT-900
This feature introduces functionality that supports deep-linking with the tabs-template.
**Historic**
Links that jump to content within tabs were not being shown. 
**Updated**
Links with a hash fragment (`http://intranet.docker/guidance/#appeal`) will open the tab where the hash is first detected. The page will then scroll to the content.
=> CDPT 900 - link to content inside tab

web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/campaign-category.php, web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/content-category.php
Fix campaign categories being overwritten by users from different agencies.
Add a function called `has_attached_terms_not_in_context` to catch if a post has a category attached that does not relate to current agency context.
Add a property called `run_has_attached_terms_not_in_context` to enable this on a taxonomy basis. Currently enabled for `Campaign_Category`, could also be enabled for other taxonomies that extend `Content_Category` e.g. `News_Category`.
Resolves: https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?selectedIssue=CDPT-1253
=> Fix campaign categories being overwritten by different agencies

web/app/themes/clarity/src/components/c-intranet-switcher/view.php
=> Agency switcher: change OSPT link from external to internal.

composer.json, composer.lock
For use on dev Cloud Platform.
This could be a temporary move, or more permanent, with some work to disable these packages in production.
Edit: this is necessary because for the development environment on Cloud Platforms, composer is installed without dev dependencies i.e. with `--no-dev`
=> Move composer packages from require-dev to require. 

.env.example, Dockerfile, composer.json, composer.lock, config/wp-offload-media.php, deploy/config/local/Caddyfile, docker-compose.yml, public/app/themes/clarity/functions.php, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-tweaks-for-minio.php
This PR adds minio & caddy which are local equivalents to S3 and CloudFront respectively.
There is also a quick fix in the Dockerfile to lock the versions for now. (Damien & I have started work on a better fix).
To get this running locally, copy the added env vars from the example.
DELIVERY_DOMAIN can be commented or uncommented.
=> Add minio & caddy for local S3.

public/app/mu-plugins/moj-auth.php, public/info.php
REMOTE_ADDR was returning an internal IP address.
=> CDPT-887 Use HTTP_X_REAL_IP instead of REMOTE_ADDR for IP allow list.

.github/workflows/deploy.yml, deploy/development/deployment.tpl, deploy/development/secret.tpl, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
This PR creates a `cloudfront-input` secret.
That means that we don't need to have our trusted public keys hardcoded in out `cloudfront.tf` file.
A change to `deploy.yaml` will allow us to rotate the trusted public keys with a grace period. Meaning that during key rotation we do not need to update the PEM values in our app and CloudFront at exactly the same instant. And, visitors with recently signed cookies will still have access to assets for a short while.
There are also a couple of typo fixes.
=> cloudfront-input secret for terraform. A/B public keys allows for key rotation with grace period.

web/app/themes/clarity/acf-json/group_667d8381383f1.json, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-admin.php, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner.php
This PR addressed the view of the Prior Party Banner:
- Comment the code
- Make end date inclusive, to match the admin WP_Query
- Improve repeater fields instructions
- Only use time_context when a banner's end date has not been passed
- Update logic around checking for editor or filtering out inactive banners
As time_context is not always set for editors, use show_inactive query string.
- Fix shortcodes, render in correct place and with correct spacing.
=> CDPT-1773 - Prior party banner add comments, end date inclusive.

web/app/themes/clarity/acf-json/group_667d8381383f1.json, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-admin.php, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-email.php, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-events.php, web/app/themes/clarity/inc/mail.php
This PR includes:
- Formatting of timestamps to local times
- Scheduled emails
- A fix for double ? in urls - including it here because it fixes a bug. Happy to change it if needs be.
The email content looks like:
feedback is welcome.
=> Localise times add add scheduled emails

web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-admin.php, web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-events.php
This PR schedules a weekly event at 01:35
This runs an action to identify events older than 1 year and deletes them.
The most recent event is kept, so that we can always see who set the current toggle status.
=> CDPT-1773 Delete events older than a year (but keep one).

Dockerfile
Fixes
```
2024/07/30 07:54:37 [emerg] 1#1: open() "/etc/nginx/php-fpm-auth.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:145
```
=> Copy /etc/nginx/php-fpm-auth.conf to build nginx

.github/README.md
This PR adds docs surrounding the IP allow list and OAuth flow.
It also removes an unnecessary extra closing `div` tag.
To see the rendered sequence diagrams. check https://github.com/ministryofjustice/intranet/tree/CDPT-1893-auth-docs
=> CDPT-1893 Add auth docs.

deploy/staging/deployment.tpl.yml
When we release new updates, Kubernetes will destroy a pod and create a new one in its place.  It will do this in a non-destructive way, always leaving a working pod behind should the update fail.
In our scenario, we were saying that 100% of 4 pods can be alive (8) and zero pods can be unavailable during the update. This is strict and unnecessary.
Our new settings allow Kubernetes to permit 50% of pods above the allowed (2 extra pods = 6) and the max unavailable is 50% meaning we always have 2 pods that are healthy and running during the update, this = no downtime in a controlled manner.
=> Adjust the update strategy

.github/workflows/ip-ranges-configure.yml
Post deploy, check with:
```
NSP=intranet-dev 
kubectl -n $NSP get secrets intranet-dev-base64-secrets -o json | jq -r  ".data.IPS_FORMATTED" | base64 -d
```
If there are newlines between ips then this PR has worked.
=> Add newlines to ips_formatted

deploy/config/local/nginx/server.conf, deploy/config/server.conf, deploy/development/deployment.tpl.yml, deploy/development/service-monitor.yml, deploy/development/service.yml, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php, public/app/themes/clarity/inc/metrics.php
This code has been live patched into dev and works as planned.
We have service metrics getting into Prometheus
e.g. The crucial metric showing a 401 and that basic auth is turned on.
https://prometheus.cloud-platform.service.justice.gov.uk/graph?g0.expr=http_status_code_wp_home&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h
=> CDPT-1239 Create service monitor and fix service metrics formatting.

deploy/development/service-dashboard.yml, deploy/production/secret.tpl.yml
This PR adds:
A basic dash to help visualise the metrics from the service monitor
A Slack webhhok secret - required by Cloud Platform team for custom alerts.
=> Add a basic service dashboard and slack webhook secret.

public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
This PR fixes a bug where ewww could not optimise images on demand.
Behind the scenes 
1.  a http request was being made
2. A signed cooke was being added to the request, but it was for all of the cdn content but only via http
3. Access was denied to the cdn (https://cdn...), so images couldn't be downloaded and optimied.
Solution: the signed cookie policy should have the correct scheme/protocol as defined by the request $url.
=> CDPT-1928 - Ensure correct scheme when signing cookies for php's request to cdn.

deploy/config/local/nginx/server.conf, deploy/config/server.conf, deploy/demo/deployment.tpl.yml, deploy/demo/network-policy.yml, deploy/demo/pod-monitor.yml, deploy/demo/service-monitor.yml, deploy/demo/service.yml, deploy/development/alerts.yml, deploy/staging/deployment.tpl.yml, deploy/staging/network-policy.yml, deploy/staging/pod-monitor.yml, deploy/staging/service-monitor.yml, deploy/staging/service.yml
This PR:
- Adds `$ip_skip_oauth`, this allows us to block `Cloud Platform IPs` from accessing the service.
This in turn means the `metrics/service` endpoint will correctly report a status code of 401 when trying to access the homepage on staging & production.
- ServiceMonitors and PodMonitors have been declared for Demo and Staging environments.
- Alerts have been declared for dev, after this PR, similar alerts will be set for demo and staging.
=> CDPT-1239 - Update nginx config and add service & pod monitors.

deploy/config/server.conf
Re use of 404s here.
I've used them, else it redirects the user to login.
> Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses
=> CDPT-1239 Correctly allow access to `/metrics/service`

.github/workflows/deploy.yml, .github/workflows/ip-ranges-configure.yml
This change is required to get metrics from the service and pods even when `IGNORE_IP_RANGES=true`.
It's the reason we don't have the intranet-demo namespace in this dashboard
https://grafana.live.cloud-platform.service.justice.gov.uk/d/bdwyqxz07sxkwg/intranet-service?orgId=1&var-namespace=intranet-staging
=> CDPT-1239 If IGNORE_IP_RANGES is true, still set local and cloud platform IP groups.

deploy/demo/alerts.yml, deploy/development/alerts.yml, deploy/development/service-dashboard.yml
This PR removes 2 unnecessary alerts and updates the dashboard.
This is because, when basic auth is enabled (on dev and demo), there is no way to test for a 400 status from the nginx pod.
=> CDPT-1239 Update dashboard and alerts to cater for basic auth on dev & demo.

public/app/themes/clarity/inc/admin/plugins/wp-elasticsearch.php
This PR modifies the way entries are removed from the array in `removeUnsetFields`.
As the array entries are indexed (not associative), `unset` has been changed to a `filter`.
=> Fix: ElasticPress. Filter out post_author and other unused fields.

bin/fpm-readiness.sh, bin/fpm-status.sh
This PR fixes syntax in `fpm-readiness.sh`, it also adds a helper script to get the status of fpm processes.
=> Fix fpm-readiness syntax & add status script

composer.json, composer.lock
This PR should fix `WPDocumentRevisions is not defined` error.
=> Update WP Document Revisions to fix JS WPDocumentRevisions is not defined.

bin/fpm-status.sh, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
For the status script, remove html from the query string, so that the output is in table layout.
For CloudFront, correctly decode the Policy cookie, from base64.
Prior to this fix, remainingTimeFromCookie was always returning 0, and issuing CF cookies on every request 🤦‍♂️
=> Fix a bug in CloudFront signing and in fmp-status script.

.env.example, .github/workflows/build.yml, .github/workflows/deploy.yml, Dockerfile, bin/local-run-s3-push.sh, deploy/config/init/s3-push-start.sh, deploy/development/job.tpl.yml, public/app/themes/clarity/functions.php, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-assets.php
This PR allows for theme, plugin and WordPress core assets to be synced to S3 and served via the CDN.
It can be broken down into parts/stages:
1. A build step to create a docker image that contains all of the assets.
2. A job is run at deploy time to run the docker image on Cloud Platform, this job syncs the assets to S3.
3. The application checks that the files are available via S3, if they ar the asset urls are re-written from https://intranet... to https://cdn.intranet...
=> CDPT-2186 Create a new container to push static assets as a k8s job.

public/app/themes/clarity/functions.php, public/app/themes/clarity/inc/admin/plugins/co-authors-plus.php, public/app/themes/clarity/inc/admin/transient-admin-notices.php
This PR shows the user any errors that the plugin co-author-plus generates.
This will assist in understanding the problem. Previously the user would have seen the generic 500.html error page.
=> CDPT-2013 Show co-author-plus errors as admin notices - instead of 500.html

config/application.php
This is a reaction to seeing a 500 error on staging - having searched the logs, there was no indication of the cause.
This PR adds logging to `/dev/stderr`, it still does *not* display errors.
=> Turn on debug log for all envs.

config/application.php
Info in ticket: https://dsdmoj.atlassian.net/browse/CDPT-2231
=> CDPT-2231 Explicitly set cookie paths to prevent conflicts in wp session cookies.

bin/composer-post-install.sh, public/app/themes/clarity/inc/admin/plugins/co-authors-plus.php
There is a bug where the [notify dashboard](http://intranet.docker/wp/wp-admin/index.php?page=notify-dashboard) was firing a fatal php error.
This was because the plugin was not setting the text-domain correctly. This has been fixed in the upstream git repo and a patch fix in this PR.
In a defensive programming move, `coauthors_filter_text` has been changed so that text domain is an optional string.
`$post?->post_type` should also fix the warning `Attempt to read property "post_type" on null`
=> Bug/CDPT-2258 Handle empty post and text domain. Add constructor to notify-for-wordpress

deploy/development/deployment.tpl.yml
The aim of this PR is to see if we can determint the root cause of CPU spikes that are happening on production.
By isolating cron tasks to a dedicated deployment, we can more easily see if it is a scheduled task that is causing the CPU spikes.
Steps to create the new deployment:
- Duplicated the existing deployment.
- The cron container is removed from the original deployment.
- The new deployment is named and labeled as `${KUBE_NAMESPACE}-cron`
=> Create a new deployment that handles cron tasks

Dockerfile, deploy/config/php-pool.conf
=> fpm log slow queries and install `strace` on fpm containers.

Dockerfile, deploy/config/php-pool.conf, docker-compose.yml, public/app/themes/clarity/functions.php, public/app/themes/clarity/inc/security.php, public/app/themes/clarity/inc/updates.php
- Log Relay (Redis) errors to stderr.
A note on memory limit: https://relay.so/docs/1.x/configuration#memory-limits
- fpm to not log every request, it's makes the logs too noisy.
- Filter out known hosts from pre_http_request logging - to remove noise from the logs.
- Prevent API requests for core, theme and plugin versions.
=> Improve logging

Dockerfile, deploy/development/config.yml, deploy/staging/config.yml
=> Add compression and eviction policy to in-memory cache.

deploy/config/local/nginx/server.conf, deploy/config/server.conf
Previously a missing file caused an error. Now it's a 404 without an error.
Before:
```
[error] 30#30: *22939 open() "/var/www/html/public/app/themes/clarity/dist/globals/fonts/moji-clarity.ttf" failed (2: No such file or directory), client: 172.20.163.241, server: localhost, request: "GET /app/themes/clarity/dist/globals/fonts/moji-clarity.ttf?vklv4a HTTP/1.1", host: "intranet.justice.gov.uk", referrer: "https://intranet.justice.gov.uk/app/themes/clarity/dist/css/style.css?id=403678736ef4bf78b9131a99ad902082"
```
After:
```
172.21.0.8 - - [20/Nov/2024:16:19:12 +0000] "GET /app/themes/clarity/dist/globals/fonts/moji-clarity.ttf HTTP/1.1" 404 1375 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "192.168.65.1"
```
=> CDPT-2264 Improve nginx's file serving.

public/app/themes/clarity/inc/amazon-s3-and-cloudfront.php
A report came in that documents are missing since migration.
This is because documents are linked inside of posts and pages with urls in the format `/wp-content/uploads/*`
This PR catches these 404s and redirects the request to the CDN, if the requested document/media exists.
=> Redirect local media URLs to cdn URLs.

public/app/mu-plugins/moj-auth/traits/oauth.php
This PR will give us better logging to diagnose OAuth related errors.
Before: 
```
[15-Jan-2025 11:07:12 UTC] MOJ_AUTH: Error: invalid_grant 
```
After:
```
[15-Jan-2025 11:07:12 UTC] MOJ_AUTH: Error: invalid_grant 
[15-Jan-2025 11:07:12 UTC] MOJ_AUTH: Error:  Array
(
[error] => invalid_grant
[error_description] => AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: 12e93405-8f34-4be2-9965-9b4780501100 Correlation ID: 27d90d53-2997-456b-8065-923945891271 Timestamp: 2025-01-15 11:07:12Z
[error_codes] => Array
(
[0] => 9002313
)
[timestamp] => 2025-01-15 11:07:12Z
[trace_id] => 8f34-4be2-9965
[correlation_id] => 2997-456b-8065
[error_uri] => https://login.microsoftonline.com/error?code=9002313
)
```
=> Add error description to OAuth callback errors.

bin/composer-post-install.sh, public/app/themes/clarity/inc/admin/plugins/wp-document-revisions.php
Reluctantly, I had to use composer-post-install.sh script to fix this bug.
The script adds 2 filters to wp-document-revisions functions.
These filters are then used in the theme to correct the author name in 2 places on the document edit screen.
=> CDPT-2265 wp-document-revisions - correct the most recent revision author

Dockerfile
Don't merge (and deploy) until https://github.com/ministryofjustice/wordpress-base-fpm/pull/31 has been merged and built.
=> CDPT-2574 Remove the phpredis class as it's will be added to the base image.

composer.json, composer.lock, deploy/config/init/fpm-start.sh, public/app/themes/clarity/inc/amazon-s3-and-cloudfront-assets.php
This PR:
- Removes WP Media Offload Pro from the mu-plugins folder, to plugins.
- Installs WP Media Offload Lite to the plugins folder.
- Adds code to the fpm container startup script, to ensure at least one of the WP Media Offload plugins is active.
- Adds theme compatibility for the Lite version.
=> CDPT-2601 Downgrade to WP Media Offload Lite

.github/workflows/codeql.yml
This PR addresses the `Unable to validate code scanning workflow: MissingPushHook` warning shown here: https://github.com/ministryofjustice/intranet/actions/runs/15159460720
=> Run CodeQL on push to main.

deploy/production/ingress.tpl.yml
Related:
- https://github.com/ministryofjustice/cloud-platform-environments/pull/33736
- https://github.com/ministryofjustice/cloud-platform-environments/pull/33737
The redirect uses a the syntax that is used in the dev ingress.
https://github.com/ministryofjustice/intranet/blob/e72e6356382177c37f9e67071a2bc0a7cd40e385/deploy/development/ingress.tpl.yml#L14
=> Redirect traffic for jac.intranet.service.justice.gov.uk to intranet.justice.gov.uk/?agency=jac

public/app/themes/clarity/src/globals/js/auth-heartbeat.js
This is a follow on PR for https://github.com/ministryofjustice/intranet/pull/867
It fixes a bug where a user could have new JS but old html from the server. And an error will occur saying mojAuthHeartbeat is undefined.
=> Handle rollout period where a user may have new js, but old server side html.

public/app/themes/clarity/src/components/c-content-filter/view-events.php, public/app/themes/clarity/src/components/c-content-filter/view-region-events.php, public/app/themes/clarity/src/components/c-content-filter/view-regions.php
Months were not rendering correctly when the current day was the 31st of a month.
e.g. July 31st plus 2 months is October and July 31st plus 3 months is also October
The fix was to set a base timestamp as the 15th of the current month, this way we don't get rounding errors when adding months.
Reference https://www.php.net/manual/en/function.strtotime.php
=> CDPT-2950 Fix date rounding bug.
