ministryofjustice/intranet

- composer.json
- docker/moj.json
By pointing it at the correct repo and adding back in the top-level
composer config file.
> Fix breaking composer container build

- docker/build.sh
It complains if this directory is missing
> Fix s3 filesystem startup warning

- wp-content/themes/mojintranet/inc/api.php
- wp-content/themes/mojintranet/inc/taxonomies/agency.php
- wp-content/themes/mojintranet/inc/taxonomies/campaign-category.php
- wp-content/themes/mojintranet/inc/taxonomies/news-category.php
- wp-content/themes/mojintranet/inc/taxonomies/region.php
- wp-content/themes/mojintranet/inc/taxonomies/resource-category.php
by making taxonomies available as public filters to WP
> Make API filter argument work

- wp-content/themes/mojintranet/inc/taxonomies/agency.php
By making the taxonomy respond to agency_filter
> Fixed agency parameter causing conflict

- docker/utils/prepare-local-wordpress-database.rb
- wp-content/themes/mojintranet/inc/taxonomies/region.php
so default test users can work
> Assign region and agency to test users

- docker/docker-compose-dev.yml
So we can easily build queries against the local container.
> Enable mysql connections locally

- wp-content/themes/mojintranet/inc/api.php
so the API can be queried using the same sorting logic and filtering as we use on the FE.
> Added custom endpoint for events, regional events

- wp-content/themes/mojintranet/inc/comments.php
so when creating a new post the checkbox is ticked and the comments are enabled
> Set comment status to open by default

- docker/utils/prepare-imported-wordpress-database.rb
This script can be run on a developer's local machine, with a
port-forward to target the required database.
> Add a ruby script to rewrite URLs in the database

- docker/utils/prepare-imported-wordpress-database.rb
* Make it clear that 'DOMAIN' should include the 'https://' prefix
* Wrap the password in single quotes, because the prod password
contains special characters
> Tweak the DB cleanup script

- wp-content/themes/mojintranet/inc/api.php
so the homepage news results don’t include featured news
> Created API endpoint for homepage news

- wp-content/themes/mojintranet/models/my_moj.php
as they are moving to another address
> Changed link to LAA intranet

- wp-content/themes/mojintranet/inc/taxonomies/agency.php
after it was changed to be agency_filter instead of agency so API works (agency is the parameter to change agency on the FE)
> Make the back-end use the agency filter right

- wp-content/themes/mojintranet/models/my_moj.php
> Changed link Travel on My HMCTS

- wp-content/themes/mojintranet/inc/api.php
so it doesn’t include items featured on the featured section
> Added endpoint to homepage blog posts

- docker/moj.json
This changes composer to pull in the master branch of Clarity theme (as we do with other themes).
> Changing composer to pull master branch from Clarity 

- docker/etc/nginx/sites-available/server.conf
Assets currently lack good Cache-control headers. This fixes that.
> Optimise asset caching

- docker/etc/nginx/sites-available/server.conf
This should have been 'd' instead of 'day'. Fixed.
> Keep the code pipeline from hanging

- wp-content/themes/mojintranet/models/my_moj.php
Added in the JO requested apps. I re-used existing icons. If JO want newly designed icons, we will have to get a designer on it and then swap those in.
> Added the requested apps to the MyJO section.

- wp-content/themes/mojintranet/models/agency.php
To be merged into master when JO approve link be removed.
> Removed legacy intranet link above apps in My MoJ on JO homepage.

- wp-content/themes/mojintranet/assets/css/src/modules/_main_nav.scss
JO wanted their own custom About Us page. This allows for a custom WP menu button that links to the new About us page.
> Added custom JO about us button.

- wp-content/themes/mojintranet/assets/css/src/modules/_agency_overlay.scss
Still needs the JO logo added. This will need to be done via a graphics program to agency_logos_x2.png and agency_logos.png. Do not merge until JO has approved button to be added.
> Added JO link to the agency list on the intranet agency switcher. 

- docker/moj.json
The other changes are merged, but this one got missed as I failed to
look at the checklist before starting :(
> Change intranet to pull from the master branch

- smoke-tests/wait-for-wordpress.sh
This will prevent the race condition seen on travis whereby one of the
supporting containers fails to start (in that case it was the mariadb
container), but the smoketest container carries on in a wait-state.  On
travis I believe the timeout for something like this is 30 minutes.
By checking that the supporting containers are all alive at the same
time we check for WP readiness, we ensure that the tests will fail
within ten seconds of any other container failling.
> Fail the entire run if supporting containers fail

- docker/moj.json
I merged the branch to master without updating this.
> Fix broken dw-mvc package

- wp-content/themes/mojintranet/inc/taxonomies/agency-terms-walker.php
Does not appear to have consequences outside newRelic error. @todd or @vinhnguyen0429  when you have a chance to review.
> Used catch exception on a newRelic error being generated.

- wp-content/themes/mojintranet/views/pages/campaign_landing/main.php
- wp-content/themes/mojintranet/views/widgets/news_list/main.php
- wp-content/themes/mojintranet/views/widgets/posts/main.php
This fixes the broke campaign hub template by using the new Clarity API call.
> Integrate WP API legacy campaign hub

- docker/Makefile
- docker/bedrock.json
Upgrading Wordpress to the latest version. 4.9.7.
> WP upgrade

- docker/etc/nginx/snippets/headers.conf
I previously used a lower number for testing but this is a more appropriate timeframe.
> Increased HSTS to two years. Common HSTS max-age setting

- docker/config/environments/development.php
Provides support to our Query Monitor plugin.
> Added support for our debug plugin querymonitor

- docker/etc/nginx/sites-available/server.conf
- docker/etc/nginx/snippets/headers-preflight.conf
- docker/etc/nginx/snippets/headers.conf
Implementing access control headers as per recommendation of pen test.
> Added access control headers

- docker/moj.json
> Added new Poll plugin

- docker/moj.json
Updated to the latest version of ACF.
> Updated ACF

- docker/moj.json
> Added Notify For WP plugin. Updated WP Query plugin.

- docker/moj.json
Changed branch to pull from master rather than clarity branch which has
now been deleted
> Updated moj.json

- wp-content/themes/clarity/inc/enqueue.php
> Update css version number.

- wp-content/themes/clarity/agency-switcher.php
- wp-content/themes/clarity/src/components/c-intranet-switcher/view.php
- wp-content/themes/clarity/views/components/c-intranet-switcher/view.php
YJB have requested a new link be added to the intranet agency switcher.
> Add YJB link to intranet switcher

- wp-content/themes/clarity/src/components/c-logo-bar/view.php
- wp-content/themes/clarity/views/components/c-logo-bar/view.php
Switcher syntax was not quite right, we only want switcher to disapear
when on switcher page but be on every other page.
> Fix switcher logic

- wp-content/themes/clarity/inc/uploads.php
Users have reported some browsers not downloading the file in the
correct way. This is likely due to the browser "guessing" at the file
type. This forces the browser to accept a particluar type.
> Update and add MIME types due to download issues

- wp-content/themes/clarity/inc/enqueue.php
- wp-content/themes/clarity/src/components/c-external-services/style.styl
- wp-content/themes/clarity/src/components/c-logo-bar/style.styl
- wp-content/themes/clarity/src/components/c-logo-bar/view.php
- wp-content/themes/clarity/src/components/c-main-nav-bar/style.styl
- wp-content/themes/clarity/src/components/c-phase-banner/style.styl
The external link list, intranet switcher button and main menu were all
jumbled up. They now all list out nicely. Tested on most main mobile
devices. Avoided implementing hamburger menu as it seems to be going out
of fashion within UX community.
> Improve main header menus on mobile

- wp-content/themes/clarity/inc/cookies.php
Call the cookie earlier in the request chain.
> Fix cookie error

- wp-content/themes/clarity/inc/whitelisted-emails.php
> Add ppo.gov.uk email to whitelist

- wp-content/themes/clarity/inc/admin/hide-templates-from-editors.php
- wp-content/themes/clarity/inc/admin/lefthand-menu.php
- wp-content/themes/clarity/inc/admin/users/add-agency-admin.php
- wp-content/themes/clarity/inc/admin/users/add-regional-editor.php
- wp-content/themes/clarity/inc/admin/wp-admin-bar.php
- wp-content/themes/clarity/inc/post-types/news.php
- wp-content/themes/clarity/inc/post-types/regional-news.php
- wp-content/themes/clarity/inc/post-types/team-area.php
Fixed a number of PHP notices and bugs relating to permissions. Plus regional editor bug relating to them not being able to delete published pages.
> Permissions

- wp-content/themes/clarity/inc/admin/agency_taxonomies/taxonomies/agency.php
- wp-content/themes/clarity/inc/admin/agency_taxonomies/utilities/agency-context.php
- wp-content/themes/clarity/inc/admin/users/add-agency-editor.php
When creating new Agency Editors their assigned agency was not being set
correctly for them.
> Fix agency editor permission bug

- wp-content/themes/clarity/page.php
- wp-content/themes/clarity/page_campaign_content.php
- wp-content/themes/clarity/page_guidance_and_support.php
- wp-content/themes/clarity/page_media_grid.php
Fixes to breadcrumb and campaign content
> Hotfix breadcrumbs

- web/app/themes/clarity/page_campaign_landing.php
Adds the excerpt custom field.
> Added Excerpt to campaign hub template

- web/app/themes/clarity/acf-json/group_5e4bf0fe004b9.json
- web/app/themes/clarity/inc/acf.php
- web/app/themes/clarity/src/components/c-agency-wide-banner/style.styl
- web/app/themes/clarity/src/components/c-agency-wide-banner/view.php
eg. service update, emergeny or bridges
> Agency Wide Banner - Now can have a banner type

- web/app/themes/clarity/error-pages/403.html
Update the 403 page to give staff more information on a common connection issue.
> 403 content update

- web/app/themes/clarity/acf-json/group_5e96c69b34f0b.json
- web/app/themes/clarity/functions.php
- web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies.php
- web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/agency.php
- web/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/workplace.php
- web/app/themes/clarity/inc/admin/comments.php
- web/app/themes/clarity/inc/comments.php
- web/app/themes/clarity/inc/post-types/condolences.php
- web/app/themes/clarity/single-condolences.php
- web/app/themes/clarity/src/components/c-breadcrumbs/view-condolence.php
- web/app/themes/clarity/src/components/c-comment-form/view-condolence.php
- web/app/themes/clarity/src/components/c-comments/view-condolence.php
- web/app/themes/clarity/src/components/c-condolence/component.json
- web/app/themes/clarity/src/components/c-condolence/style.styl
- web/app/themes/clarity/src/components/c-condolence/view.php
Added Condolence post type
Added Workplace taxonomy
Created new view for comments section (renamed Message)
Removed reply and likes.
Theres some auto tidying of code in /inc/comments.php
> Condolence part1

- web/app/themes/clarity/page_condolence_listing.php
- web/app/themes/clarity/src/components/c-condolence-header/component.json
- web/app/themes/clarity/src/components/c-condolence-header/style.styl
- web/app/themes/clarity/src/components/c-condolence-header/view.php
- web/app/themes/clarity/src/components/c-condolence/style.styl
- web/app/themes/clarity/src/components/c-condolence/view-list.php
- web/app/themes/clarity/src/components/c-condolence/view.php
- web/app/themes/clarity/src/components/c-condolences-list/component.json
- web/app/themes/clarity/src/components/c-condolences-list/style.styl
- web/app/themes/clarity/src/components/c-condolences-list/view.php
- web/app/themes/clarity/src/components/c-content-filter/view-condolences.php
- web/app/themes/clarity/src/globals/js/condolences-filter.js
- web/app/themes/clarity/src/globals/js/script-loader.js
I have created a list and grid view with a switcher. So we can decide to keep one..or both.
> Condolence listing

- docker-compose.yml
- web/app/themes/clarity/src/components/c-homepage-secondary-widget/view.php
On request of LAA add a small box/widget on the homepage that show's the latest event.
> Add LAA homepage events widget

- web/app/themes/clarity/inc/post-types/regional-news.php
Make the dropdown less confusing for editors.
> Fix double title bug in admin dropdown

- composer.lock
- web/app/themes/clarity/package-lock.json
- web/app/themes/clarity/package.json
Plugins and WP Updated
For some reason the elasticpress plugin was in the composer lock file.
> Security Updates

- web/app/themes/clarity/inc/uploads.php
Restrict upload media so videos can no longer be uploaded
> Video uploads

- web/app/themes/clarity/search.php
* Takes new banner code from our `elasticsearch` branch so that we can use it on intranet-v3 staging for testing and eventually in our final release.
> Intranet v3 cherrypick

- web/app/themes/clarity/search.php
* Request to change the survey link for intranet search to new link.
> Update search survey with new link

- composer.json
- composer.lock
- web/app/themes/clarity/package-lock.json
Updated all plugins
Updated wordpress version from 5.7
> Update composer and wordpress 5.8

- web/app/themes/clarity/inc/agency.php
- web/app/themes/clarity/inc/whitelisted-emails.php
* Add OSPT email to allowlist
* Refactor agency tag ID to be dynamic. To do this I pulled the agency array into the function so that it can be looped over.
> Add OSPT email to allowlist and refactor agency tag ID

- web/app/themes/clarity/src/components/c-article-byline/view.php
- web/app/themes/clarity/src/components/c-article-featured-image/view.php
- web/app/themes/clarity/src/components/c-article-item-feature/view.php
- web/app/themes/clarity/src/components/c-article-item/view-blog-feed.php
- web/app/themes/clarity/src/components/c-article-item/view-blog.php
- web/app/themes/clarity/src/components/c-article-item/view-blogfeature.php
- web/app/themes/clarity/src/components/c-article-item/view-date.php
- web/app/themes/clarity/src/components/c-article-item/view-date_excerpt.php
- web/app/themes/clarity/src/components/c-article-item/view-news-feed.php
- web/app/themes/clarity/src/components/c-article-item/view-newscategory.php
- web/app/themes/clarity/src/components/c-article-item/view-regions.php
- web/app/themes/clarity/src/components/c-article-item/view-team-feature.php
- web/app/themes/clarity/src/components/c-article-item/view.php
- web/app/themes/clarity/src/components/c-blog-article-item/view.php
- web/app/themes/clarity/src/components/c-news-article-item/view.php
Added aria-hidden to decorative image and removed alt text for decorative images
> Alt txt update

- web/app/themes/clarity/src/components/c-footer-nav/view.php
- web/app/themes/clarity/src/components/c-global-header/base-header.php
- web/app/themes/clarity/src/components/c-logo-bar/view.php
• Logo - alt text removed and added aria-hidden to link.
• Page Titles - reformatted to GDS format.
• Navigation tag - removed from footer.
> Logo, Page Titles and Navigation

- web/app/themes/clarity/src/components/c-calendar-icon/view-eventsapi.php
- web/app/themes/clarity/src/components/c-calendar-icon/view.php
- web/app/themes/clarity/src/components/c-event-listing/style.styl
- web/app/themes/clarity/src/components/c-event-listing/view.php
- web/app/themes/clarity/src/components/c-events-item-byline/style.styl
- web/app/themes/clarity/src/components/c-events-item-byline/view.php
- Headings changed from multiple H1's and H2 to H1, H2 and H3
- Span added to Time, Location and Hidden Date
> Remove duplicated headings

- web/app/themes/clarity/src/components/c-external-services/view.php
- Removed empty anchor link with a check if the url exists
> Empty anchor link removed

- web/app/themes/clarity/src/components/c-blog-article-item/style.styl
> Added padding to date

- web/app/themes/clarity/src/components/c-register/style.styl
- web/app/themes/clarity/src/components/c-register/view.php
- Added error summary with links to errors
- Amended error messages for screen name and email 
- Added class, padding and styling
> Status msg

- web/app/themes/clarity/inc/forms.php
- HMCTS agency feedback form email amended to HMCTS.Communications@justice.gov.uk
> email address updated

- web/app/themes/clarity/src/components/c-register/view.php
- added to screen name label for=id of input field
- added to email address label for=id of input field
> for added to input labels

- composer.json
- composer.lock
- wordpress updated to version 5.9.3 from 5.8.2
> updated wordpress version

- web/app/themes/clarity/src/components/c-tabbed-content/style.styl
- web/app/themes/clarity/src/components/c-tabbed-content/tabbed-content.js
- web/app/themes/clarity/src/components/c-tabbed-nav/view.php
- added keyboard tab to access different information presented using tabs
- added background colour to distinguish which tab is active
> keyboard tab added to tab

- web/app/themes/clarity/src/components/c-content-filter/style.styl
- web/app/themes/clarity/src/components/c-content-filter/view-condolences.php
- web/app/themes/clarity/src/components/c-content-filter/view-enews.php
- web/app/themes/clarity/src/components/c-content-filter/view-events.php
- web/app/themes/clarity/src/components/c-content-filter/view-region-events.php
- web/app/themes/clarity/src/components/c-content-filter/view-region-news.php
- web/app/themes/clarity/src/components/c-content-filter/view-regions.php
- web/app/themes/clarity/src/components/c-content-filter/view-tibit.php
- web/app/themes/clarity/src/components/c-content-filter/view.php
- web/app/themes/clarity/src/components/c-event-article/view-team.php
- web/app/themes/clarity/src/components/c-event-article/view.php
- web/app/themes/clarity/src/components/c-homepage-primary/view.php
- web/app/themes/clarity/src/components/c-input-container/view.php
- web/app/themes/clarity/src/components/c-news-article/view-regional_news.php
- web/app/themes/clarity/src/components/c-news-article/view.php
- web/app/themes/clarity/src/components/c-search-results-filter/style.styl
- web/app/themes/clarity/src/components/c-team-homepage-primary/view.php
- Added fieldset and legend
- Removed colon from Date, Keyword and others that use filter
- Added hint text for News and Event filters
- Amended text to Filter By
> Non desc label2

- web/app/themes/clarity/page_campaign_landing.php
- web/app/themes/clarity/page_delete_user.php
- web/app/themes/clarity/page_news.php
- web/app/themes/clarity/src/components/c-article-item/view-news-feed.php
- web/app/themes/clarity/src/components/c-article-item/view-newscategory.php
- web/app/themes/clarity/src/components/c-article-item/view-regions.php
- web/app/themes/clarity/src/components/c-article-item/view-team-feature.php
- web/app/themes/clarity/src/components/c-article-item/view.php
- web/app/themes/clarity/src/globals/js/blog-content_filter.js
- Added aria role for news search results to be announced
- Added focus for news search results
- Removed extra space from class definition
> News search

- web/app/themes/clarity/searchform.php
- web/app/themes/clarity/src/components/c-comment-form/style.styl
- web/app/themes/clarity/src/components/c-feedback-container/style.styl
- web/app/themes/clarity/src/components/c-feedback-form/view.php
- web/app/themes/clarity/src/components/c-register/style.styl
- web/app/themes/clarity/src/components/c-search-bar/style.styl
- Removed duplicate 'type="submit"' in feedback form button
- Amended aria-label to announce Search instead of Go
- Added black border to input and text boxes
- Amended link 'Is there anything wrong with this page' to correct colour when in focus
> Search bar

- composer.json
- web/app/themes/clarity/inc/form-builder.php
- web/app/themes/clarity/src/components/c-feedback-container/view.php
- web/app/themes/clarity/src/components/c-feedback-form/feedback-form.js
- web/app/themes/clarity/src/components/c-feedback-form/view.php
- the form_builder function name added to call with properties
> Feedback page

- web/app/themes/clarity/src/globals/css/_init.styl
- Focus indicator added to date selector
> Focus added to date selector

- web/app/themes/clarity/search.php
Removed banner as no longer needed
> Removed Search Feedback Banner

- web/app/themes/clarity/src/components/c-input-container/view.php
- Closing tag of textarea moved to same line as output.
> Removed spaces from textarea on feedback form

- web/app/themes/clarity/src/components/c-intranet-switcher/view.php
Preparing a change to the URL for HMPPS to coincide with their new Intranet launch date.
> HMPPS: Update Agency URL

- .github/workflows/node.js.yml
An action to check npm can compile production assets without error.
> CDPT-270 : create an Action to check NPM can compile successfully

- .github/workflows/php.yml
An action to run composer checks. Makes sure we have no errors.
> CDPT-269 : create an Action to check composer can run successfully

- web/app/themes/clarity/src/components/c-intranet-switcher/view.php
As requested reverted back to original link
> Update HMPPS intranet link back to original

- web/app/themes/clarity/functions.php
- web/app/themes/clarity/inc/EnvironmentNotice.php
Sometimes, it can be forgotten which environment we are currently working with. This admin notice aims to assist developers. This notice does not display on Production.
> Display a notice to show the current environment

- .env.example
- Dockerfile
- README.md
- composer.json
- composer.lock
- docker-compose.yml
This PR includes updates to support improving search on the Intranet. Specifically; it will launch a local copy of Elasticsearch + Kibana and allow you to index via this URL endpoint:
http://elasticsearch:9200/
In addition, security updates and patches provided via composer were installed to bring WordPress and other dependencies up to date.
> CDPT 258 Connect local Elasticsearch

- web/app/themes/clarity/inc/mail.php
- web/app/themes/clarity/src/components/c-input-container/on-change.js
- web/app/themes/clarity/src/components/c-input-container/style.styl
- web/app/themes/clarity/src/components/c-input-container/view.php
- web/app/themes/clarity/src/components/c-search-results-filter/view.php
- web/app/themes/clarity/src/globals/js/script-loader.js
Add radio buttons to filter search
> Search radios instead

- composer.lock
- web/app/themes/clarity/package-lock.json
- web/app/themes/clarity/package.json
Upgrades the following: 
* **ACF**: version 6.1.6
* **AWS SDK**: version 3.271.1
* **Like Button for WordPress**: version 381c400 (git hash)
* **EWWW**: version 7.0.1
* **Sentry**: version 3.19.1
> Security upgrade

- web/app/themes/clarity/inc/content-filter/search.php
**Ticket:**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?modal=detail&selectedIssue=CDPT-752
**Context:**
The code block where this error has been identified is called (or should be) when a form request is performed more than once. It should prevent multiple form submissions.
At some point in the past an alien character was introduced however, the git history was erased by a team member which makes it impossible to identify the root cause.
> CDPT-752 Remove alien character

- web/app/themes/clarity/inc/comments.php
- web/app/themes/clarity/inc/cookies.php
**Ticket:**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?modal=detail&selectedIssue=CDPT-534
**Context:**
Insecure cookies are present on secure pages. This PR sets secure cookies if HTTPS is detected.
---
**Nb. This PR carries [a hidden update from the intranet-base repo](https://github.com/ministryofjustice/intranet-base-docker) - it simply increases PHPs available memory to allow larger file downloads**
> CDPT-534 Use secure cookies if we can

- web/app/themes/clarity/inc/api/get-campaign-news-api.php
- web/app/themes/clarity/inc/api/get-campaign-posts-api.php
Defaults are not represented correctly. Explicitly set them.
> Fix the campaign template pages

- web/app/themes/clarity/acf-json/group_64ad54774278b.json
- web/app/themes/clarity/functions.php
- web/app/themes/clarity/inc/agency.php
- web/app/themes/clarity/inc/api/campaign-api.php
- web/app/themes/clarity/inc/api/get-campaign-news-api.php
- web/app/themes/clarity/inc/api/get-campaign-posts-api.php
- web/app/themes/clarity/package-lock.json
- web/app/themes/clarity/package.json
1. Security fix for chalk
2. Refactor of campaign-api code
3. Agency cookie code simplified
`web/app/themes/clarity/inc/agency.php`
This file has been linted; the meaningful updates are on the following lines.
* 176
* 178
> CDPT-883 HMCTS campaign support increase post amount

- web/app/themes/clarity/src/components/c-input-container/view.php
- web/app/themes/clarity/src/components/c-search-results-filter/view.php
**Context**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?selectedIssue=CDPT-918
Testing search impact using radio buttons for HMCTS has now completed. This PR activates radio buttons for HMCTS only. Once we have feedback from Intranet users, we can further consider release to the broader intranet audience.
> Configure radio buttons for HMCTS

- bin/build.sh
- composer.json
- composer.lock
- web/app/themes/clarity/package-lock.json
- web/app/themes/clarity/package.json
Use production mode when building in the pipeline
Also, update plugins for security
> Use production mode on build

- web/app/themes/clarity/src/components/c-tabbed-content/tabbed-content.js
> CDPT 900 link to content inside tab

- web/app/themes/clarity/src/components/c-search-results-filter/view.php
**Context**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?selectedIssue=CDPT-1016
> CDPT 1016 Releases radio buttons to all users

- composer.json
- composer.lock
> CDPT-1240: Intranet migration

- web/app/themes/clarity/functions.php
- web/app/themes/clarity/inc/comments.php
- web/app/themes/clarity/inc/maintenance.php
- web/app/themes/clarity/src/components/c-comment-form/view.php
- web/app/themes/clarity/src/components/c-share-post/view.php
- Add maintenance class
- Add settings page for maintenance functions
- Add functionality to enable maintenance mode and lock non-admins out of the admin section of the site
- Add functionality to display a notification banner as advanced warning for editors of upcoming maintenance
> CDPT-1475: Intranet migration - content freeze

- web/app/themes/clarity/src/components/c-intranet-switcher/view.php
- Remove JAC from intranet switcher ignore list
> CDPT-1481: Add JAC to the intranet switcher

- deploy/development/deployment.tpl
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
- Try to use basic auth in auth header directly
> CDPT-1528: Offload media

- web/app/themes/clarity/acf-json/group_667d8381383f1.json
- web/app/themes/clarity/acf-json/group_667d8a0f642b5.json
- web/app/themes/clarity/inc/acf.php
@wilson1000 , this includes a slight rename, to make the options page more flexible. Naming it to Prior Political Parties so as not to limit it to just Banner options. Do you reckon that sounds ok?
> Add options page and ACF fields for Prior Party Banner.

- web/app/themes/clarity/acf-json/group_667d8381383f1.json
- web/app/themes/clarity/inc/admin/prior-party/prior-party-banner-admin.php
- web/app/themes/clarity/inc/admin/prior-party/prior-party-banner.php
Also fixes https://github.com/ministryofjustice/intranet/pull/562#issuecomment-2209324113
> Bug fix - where editors/logged-out couldn't see banner.

- Dockerfile
- bin/composer-post-install.sh
- composer.json
- public/app/themes/clarity/functions.php
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront.php
This PR 
- adds filters to increase batch size for the AS3CF plugin.
- Adds a post instal/update script to that patches in logging to the plugin - similar to Justice UK patching technique.
> CDPT-1246 AS3CF increase batch size and add logging

- bin/composer-post-install.sh
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront.php
> Increase batch size for fix_broken_item_extra_data

- Dockerfile
- docker-compose.yml
- public/app/themes/clarity/package-lock.json
- public/app/themes/clarity/package.json
- Update node containers to `22-alpine`.
- As alpine doesn't have `make`, move install and run scripts to `docker-compose`
- Update outdated dependencies and remove `vue-template-compiler`.
- Run `npm audit` and `fix`.
> Update node containers and theme packages

- public/app/themes/clarity/inc/admin/js/feedback.js
> Put notification above ACF buttons 

- config/wp-offload-media.php
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront-for-minio.php
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
- Send signed cookies on all php's requests to the cdn.
- Allow non-https requests for local requests to local cdn.
> Debug media uploads - update internal requests to the cdn.

- .github/README.md
- deploy/production/config.yml
- deploy/production/deployment.tpl.yml
- deploy/production/secret.tpl.yml
This PR adds the bare minimum into the `deploy/production` folder, to let the github deploy action complete.
This will add the necessary secret for confluence to complete.
Later, we will add service, ingress, hpa etc.
> Add secrets and config for intranet-production namespace.

- deploy/development/service-dashboard.yml
@wilson1000 thanks for providing the updated json :)
> CDPT-1239 Update dashboard for easier/quicker reading.

- Dockerfile
- composer.json
- composer.lock
- config/application.php
- config/wp-offload-media.php
- config/wp-sentry.php
- public/app/themes/clarity/inc/amazon-s3-and-cloudfront-signing.php
- public/errors.php
There is a noticable lag on the staging stack, even with the same resources used. 
This update is to help us turn Sentry off to see if it is causing latency.
> Ability to turn Sentry on or off

- deploy/production/deployment.tpl.yml
- deploy/production/hpa.yml
- deploy/production/ingress.tpl.yml
- deploy/production/pod-monitor.yml
- deploy/production/service.yml
- deploy/staging/ingress.tpl.yml
This PR is the fist part of getting the production deployment ready.
Ingress will need some manual testing with kubectl before checking into git.
`alerts.yml`, `service-monitor.yml` & `network-policy.yml` are/will be in the cloud platform environments repo.
> Add phase 1 of production deployment

- bin/composer-post-install.sh
- composer.json
- composer.lock
- public/app/themes/clarity/search.php
- public/app/themes/clarity/src/components/c-global-header/base-header.php
This PR moves plugins integral to the Internet operation to the mu-plugins directory.
We are also applying a title to the search page. Historically, this has been omitted.
| Before    | After |
| -------- | ------- |
| ![Screenshot 2024-10-03 at 12 19 06](https://github.com/user-attachments/assets/62197b41-1c2a-4546-9d26-a300e947a533)  | ![Screenshot 2024-10-03 at 12 00 39](https://github.com/user-attachments/assets/71e465d0-fad9-454c-abed-a5749c79e7cc)    |
> Optimise plugins + base-header update

- deploy/production/deployment.tpl.yml
This looks ok on dev. Copying the deploy config to production.
> Create a new deployment that handles cron tasks - production

- public/app/themes/clarity/inc/acf.php
- public/app/themes/clarity/inc/api/intranet-v1-api.php
- public/app/themes/clarity/inc/post-types/webchat.php
- public/app/themes/clarity/src/components/c-last-updated/view.php
- public/app/themes/clarity/src/components/c-search-result-item/view.php
- Fix warnings about missing parameter.
- Fix join on null error.
- Fix deprecation warning for get_page_by_title.
- Fix Trying to access array offset on false
- Fix foreach() argument must be of type array|object, false given
> CDPT-2264 Warning log fixes

- public/app/themes/clarity/src/components/c-polls/style.styl
- public/app/themes/clarity/src/components/c-rich-text-block/style.styl
- public/app/themes/clarity/src/globals/css/_mixins.styl
- public/app/themes/clarity/src/globals/css/objects.styl
- public/app/themes/clarity/src/globals/css/reset.styl
- Update typescale to 1.125 ratio
> CDPT-636: Typescale

- composer.json
- composer.lock
- config/application.php
- deploy/development/config.yml
- deploy/staging/config.yml
- public/app/mu-plugins/moj-auth/classes/oauth-cache.php
- public/app/mu-plugins/moj-auth/moj-auth.php
- public/app/mu-plugins/moj-auth/traits/oauth.php
This POC is a change to the Entra Auth flow to use packages provided by Microsoft. In an aim to address an issue with Mobile Edge browsers.
> POC revision of Entra Auth.

- public/app/themes/clarity/src/components/c-share-post/style.styl
- public/app/themes/clarity/src/globals/css/layouts.styl
- Apply padding-top to all pages
- Reset the margins on l-full-page elements that are the first child of a page for consistency
> CDPT-2482: Page margins

- deploy/production/config.yml
This PR adds the intranet archive URL, and should be merged after the first snapshot has completed.
> CDPT-2295 Add intranet-archive URL

- public/app/themes/clarity/inc/agency.php
- Add clarification text to hmi link to reduce requests for access
> CDPT-2570: HMI Probation / Youth Custody links

- public/app/themes/clarity/inc/amazon-s3-and-cloudfront-assets.php
This PR fixes a bug where the fpm init script throws an error.
> CDPT-2601 Fix error in downgrade to WP Media Offload Lite

- public/app/themes/clarity/functions.php
- public/app/themes/clarity/inc/admin/agency_taxonomies/taxonomies/agency.php
- public/app/themes/clarity/inc/admin/users/add-agency-admin.php
- public/app/themes/clarity/inc/admin/users/add-agency-editor.php
- public/app/themes/clarity/inc/admin/users/add-notes-from-perm-sec.php
- public/app/themes/clarity/inc/post-types/archived-content.php
- public/app/themes/clarity/inc/post-types/notes-from-amy.php
- public/app/themes/clarity/inc/post-types/notes-from-antonia.php
This PR:
- Creates a specific capability for `archived_content`.
- Adds copy to the Archived Content menu page.
- Moves Notes from Amy into the Archived Content menu.
> CDPT-2807 Archived Content - Add copy, capability, and Notes from Amy

- .github/README.md
- public/app/themes/clarity/inc/api/synergy-feed-api/synergy-feed-api.php
- public/app/themes/clarity/inc/api/synergy-feed-api/traits/constants.php
- public/app/themes/clarity/inc/api/synergy-feed-api/traits/page-content.php
- public/app/themes/clarity/inc/api/synergy-feed-api/traits/routes.php
- public/app/themes/clarity/inc/api/synergy-feed-api/traits/user.php
- public/app/themes/clarity/inc/api/synergy-feed-api/traits/utils.php
This pull request will allow for a CSV to be generated with a catalog of all pages and documents relevant to the Synergy platform - as per their recent request.
> CDPT-3003 Add CSV format and documents to the Synergy API response.

- public/app/themes/clarity/inc/api/synergy-feed-api/synergy-feed-api.php
This PR fixes an error and a warning that became apparent when running the code on the dev. environment. 
- `return new WP_Error(...)` is used instead of `Throw new WP_Error(...)`.
- `is_wp_error($data)` has been used in favour of `try catch`.
- Documents without attachments are skipped in the loop, with `if (!$wpdr->get_document($document->ID))`.
> CDPT-3003 Return `WP_Error` instead of throwing it. Handle documents without attachments.
